Add Status field into Istio Objects
kiali/kiali-ui pull request #1915
Opened 2020-09-08 15:14 UTC by xeviknal

Requires https://github.com/kiali/kiali/pull/3188
Fixes #2236

There is a decoration: the status field is folded in order not to eat a lot of space and also avoid showing redundant information.

Demo:
![analyzer-messages](https://user-images.githubusercontent.com/613814/92494896-898a1c00-f1f6-11ea-930a-af98a1f44aa5.gif)

2020-09-08 15:17 UTC, lucasponce commented
> There is a decoration: the status field is folded in order not to eat a lot of space and also avoid showing redundant information.

Ah, I was to comment that :-).
The status field is an uber copy of the whole object plus additional info, so a helper to avoid this is interesting.

Note that we need to test how it works with the patches, in theory it should be transparent but there may be some corner cases that may affect the create/update scenarios.

In any case, I'll review in detail too.

2020-09-08 15:25 UTC, xeviknal commented
I was about to place the status at the end of the yaml, however, it was easier like this bc of the backend part gets easier.

Regarding the patches, I've tried to update different objects and nothing wrong happened. It looks like safe.

2020-09-09 15:12 UTC, lucasponce commented
I'm having this experience:
![image](https://user-images.githubusercontent.com/1662329/92617395-87d85b00-f2bf-11ea-8aca-84e14a8a5f5c.png)

All the fields collapsed by default.

Is that intentional ?

2020-09-09 15:14 UTC, lucasponce requested changes
Can we check that only the status field get collapsed ?
Otherwise experience is degraded when access to the Istio Config detail.

2020-09-09 15:17 UTC, lucasponce commented on src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
> +      // Fold Status field
Ok, if the status is not present, this is failing in my case I guess I didn't test it with the status enabled.

2020-09-10 09:20 UTC, xeviknal commented
@lucasponce changes approached:

Without status field, there are no fold in place nor the analyzers title in the sidepanel:
![Screenshot of Kiali Console (42)](https://user-images.githubusercontent.com/613814/92708592-873ed380-f356-11ea-9b64-6f3b46f99226.png)

With status and analyzer messages:
![Screenshot of Kiali Console (43)](https://user-images.githubusercontent.com/613814/92708588-86a63d00-f356-11ea-8995-369aec521e1a.png)

With status but no analyzer messages:
![Screenshot of Kiali Console (44)](https://user-images.githubusercontent.com/613814/92709645-61fe9500-f357-11ea-990b-a7ccb163083f.png)

2020-09-10 12:40 UTC, lucasponce approved these changes

2020-09-10 12:40 UTC, merged

2020-09-10 14:43 UTC, prachiyadav commented
![Screenshot from 2020-09-10 20-13-01](https://user-images.githubusercontent.com/13483060/92747686-74c29b00-f352-11ea-9149-5a85f14349d0.png)
![Uploading Screenshot from 2020-09-10 20-11-17.png…]()

2020-09-10 15:39 UTC, prachiyadav commented
post merge verified