Adding filters into envoy dump tables
kiali/kiali-ui pull request #2051
Opened 2021-01-13 15:43 UTC by xeviknal

belongs to https://github.com/kiali/kiali/issues/3346

Adding filters to help explore the envoy dump tables for each pod.

![proxy-filtering](https://user-images.githubusercontent.com/613814/104474495-5b5e8380-55be-11eb-99fb-adb826f41b18.gif)

2021-01-14 14:05 UTC, skondkar requested changes
Tested on Kiali UI :     1.29.0 (55fa282bdcde6138f98a863b5c0ed5da59dc463e)

Looks good in chrome, but some issue in firefox ( version 70 and 68.8)
When selecting values from 'resources' dropdown, from 'all' to 'clusters', it works, and then from 'clusters' to 'listners', it throws some error in UI:

Could not fetch envoy config routes entries for productpage-v1-6b746f74dc-qmsq5.
Details shows: Unable to listen on any of the requested ports: [{15000 15000}]

![Screenshot-PortError2](https://user-images.githubusercontent.com/6614472/104600897-997fa400-569f-11eb-9c5a-8b32502b826b.png)

2021-01-15 07:10 UTC, skondkar commented
One more observation:
When we select resources as 'Clusters' and then 'Direction' from the dropdown, the next dropdown shows values 'Direction, inbound, outbound and a hyphen as seen in the screenshot
The values should be inbound and outbound.

![Screenshot-DirectionDropdown](https://user-images.githubusercontent.com/6614472/104692743-7bad5000-572e-11eb-8bfa-0343a9fb5e41.png)

2021-01-15 12:25 UTC, xeviknal commented
@skondkar both changes approached. thanks

2021-01-18 08:26 UTC, skondkar approved these changes
Thanks @xeviknal 
Verified on Kiali UI :  1.29.0 (1c2bce8d305546e82f2036ee9b0e7e8c9528f31b)
LGTM

2021-01-18 09:28 UTC, aljesusg approved these changes
onlye one minor comment. no block, LGFM

2021-01-18 09:28 UTC, aljesusg commented on src/components/Envoy/EnvoyModal.tsx
> +      }
what do you think about
```ts
 if(this.state.fetch && (this.state.pod.name !== prevState.pod.name || this.state.resource !== prevState.resource)) {
```

2021-01-18 12:47 UTC, lucasponce commented
I guess I may ask a change in the feature.

Filter is single value:
![image](https://user-images.githubusercontent.com/1662329/104917263-7997fb00-5993-11eb-8c77-012337972551.png)

But as it happens with app/workload/service lists, multi-value would help a lot:
![image](https://user-images.githubusercontent.com/1662329/104917362-98968d00-5993-11eb-8ed5-34bcb0d3eef4.png)

For example, I'd like to filter by port 8080 or 9090:
![image](https://user-images.githubusercontent.com/1662329/104917438-b3690180-5993-11eb-9512-8de2f091b372.png)

Otherwise I'd see the filter a little bit limited (I guess it's a minor change in the filter code, component is prepared for this).

2021-01-18 12:48 UTC, lucasponce requested changes
A small change in the behaviour of the filter.

2021-01-18 15:36 UTC, xeviknal commented
@lucasponce comments approached. The behavior now is like the workloads/apps/services/istio lists. Applies OR for the same filter and AND between different filters.

2021-01-20 08:51 UTC, lucasponce approved these changes

2021-01-20 08:51 UTC, merged