Add hosts to SE node
kiali/kiali-ui pull request #2089
Opened 2021-02-23 09:38 UTC by jotak

Replacing "isServiceEntry", which wasn't actually a bool but a string
MESH_INTERNAL or MESH_EXTERNAL, with a struct holding "location" and
"hosts"

For traces, use this new "hosts" field instead of "destServices"

Fixes https://github.com/kiali/kiali/issues/3728

Backend PR: https://github.com/kiali/kiali/pull/3729

2021-02-23 10:05 UTC, jotak commented
Here's a pic of trace being "cut" before this fix:

![Capture d’écran de 2021-02-23 10-52-19](https://user-images.githubusercontent.com/2153442/108827462-eec7a300-75c5-11eb-8dce-0f84484a3119.png)

And after this fix:

![Capture d’écran de 2021-02-23 10-55-40](https://user-images.githubusercontent.com/2153442/108827497-f8e9a180-75c5-11eb-8917-db18079d7a30.png)

Note that I struggle to get the graph as desired, which I guess is because TCP edges are only built from tcp_sent telemetry, not tcp_receive. I'll open another issue about that (it doesn't affect this PR, just makes it less easy to test)

2021-02-23 14:06 UTC, jshaughn requested changes
@jotak This all looks good other than the name change.  Sorry for the churn.

2021-02-23 14:06 UTC, jshaughn commented on src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
> +        type = node.seInfo ? Paths.SERVICEENTRIES : Paths.SERVICES;
For consistency, please change this back to isServiceEntry (as mentioned on the server PR).

2021-02-23 19:18 UTC, jshaughn approved these changes
LG!

2021-02-24 07:28 UTC, jotak commented
Thanks @jshaughn 

As this is a quite narrow case, not sure if QE wants to test the whole thing or just smoke tests for non-regression.
In case you want to test all: to reproduce the initial issue you can use the mesh-arena demo with kafka:
- From repo https://github.com/jotak/demo-mesh-arena/ , install kafka: `make kafka-se`
- Wait everything is up and running in namespace kafka
- Enable istio: `make istio-enable`
- Deploy mesh-arena: `kubectl apply -f <(curl -L https://raw.githubusercontent.com/jotak/demo-mesh-arena/zizou/quickstart-kafka.yml) -n default`

Wait for the graph to be populated + wait extra time that all kafka edges appear (it takes several minutes because of https://github.com/kiali/kiali/issues/3730 )

At this point you can see the behaviours as I describe in my previous comment.

2021-02-24 16:12 UTC, hhovsepy approved these changes
Regression test passed.

2021-02-24 17:05 UTC, merged