Add MissingSidecar tooltip
kiali/kiali-ui pull request #2114
Opened 2021-03-30 12:44 UTC by lucasponce

Fixes https://github.com/kiali/kiali/issues/3535

![image](https://user-images.githubusercontent.com/1662329/112990417-55605380-9166-11eb-805c-7bb6693e22cb.png)

2021-03-30 12:51 UTC, jshaughn requested changes

2021-03-30 12:51 UTC, jshaughn commented on src/components/MissingSidecar/MissingSidecar.tsx
> +      "Istio container doesn't found in Pod(s). Check if the istio-injection label/annotation is correctly set on the namespace/workload.",
grammar --> "Istio container not found in Pod(s)."    Or perhaps "Istio sidecar container not found in Pod(s)."

2021-03-30 12:51 UTC, jshaughn commented on src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
> +                    textTooltip="Istio container doesn't found in Pod(s). Check if the istio-injection label/annotation is correctly set on the namespace/workload."
ditto

2021-04-08 03:03 UTC, lucasponce commented
@hhovsepy @jshaughn what is missing in this PR ?

2021-04-08 07:03 UTC, hhovsepy approved these changes

2021-04-08 13:17 UTC, jshaughn approved these changes
Nothing missing, sorry, fell off the radar.

2021-04-09 07:03 UTC, merged