Added help icon and tooltip on Metrics tab Reported from dropdown.
kiali/kiali-ui pull request #2234
Opened 2021-09-06 19:07 UTC by hhovsepy

Fix for RFE https://github.com/kiali/kiali/issues/1433

![Screenshot from 2021-09-06 21-04-34](https://user-images.githubusercontent.com/604313/132254685-b8095124-acc5-456b-bd05-aaefb4d5ca8b.png)

2021-09-07 18:20 UTC, leandroberetta requested changes
Just a minor typo, the rest LGTM.

2021-09-07 18:20 UTC, leandroberetta commented on src/components/MetricsOptions/MetricsReporter.tsx
> +            which emitted the requested) and by the Destination (workload which received the request). In general, the
```suggestion
            which emitted the request) and by the Destination (workload which received the request). In general, the
```

2021-09-07 18:39 UTC, hhovsepy commented
Thank you @leandroberetta , changed the typo.

2021-09-09 15:17 UTC, leandroberetta approved these changes
LGTM

2021-09-09 15:38 UTC, merged