Graph shorcuts in Graph Tour
kiali/kiali-ui pull request #2244
Opened 2021-09-23 14:21 UTC by leandroberetta

This PR adds a new stop in the graph tour to show the shortcuts available in the graph.

This is a work in progress draft PR to get feedback:

![shortcuts](https://user-images.githubusercontent.com/1286393/134524459-c25386c0-234c-4c20-aec9-66ca33472a2f.png)

Resolves [#4133](https://github.com/kiali/kiali/issues/4133)

2021-09-23 14:22 UTC, leandroberetta commented
@lucasponce @jshaughn based on the comments on the issue, I tried to mix some ideas and comments resulting in the screenshot above.

There are shortcuts missing but I created this to start discussing about the design.

2021-09-24 13:55 UTC, jshaughn commented
@leandroberetta I like the idea of making "Shortcuts" the first tour stop.  It leverages the fact that we already have this feature in place.  And if the user just wants to see Shortcuts he can exit the tour immediately.  We may want to rename "Graph tour" to "Shortcuts and tips", or something like that, to ensure users know they can look there.  I'm not sure "Graph tour" has ever been particularly enticing.  Also, the word "Graph" is pretty useless, it's already implied.

2021-09-24 14:01 UTC, leandroberetta commented
> @leandroberetta I like the idea of making "Shortcuts" the first tour stop. It leverages the fact that we already have this feature in place. And if the user just wants to see Shortcuts he can exit the tour immediately. We may want to rename "Graph tour" to "Shortcuts and tips", or something like that, to ensure users know they can look there. I'm not sure "Graph tour" has ever been particularly enticing. Also, the word "Graph" is pretty useless, it's already implied.

@jshaughn thanks for the comments, I agree, I even thought in removing the description, just leaving the help icon... following the same pattern in the factory reset button

2021-09-24 14:13 UTC, lucasponce commented
Reusing the tour for the shortcuts seems ok.

Perhaps a little bit out of context as other users may prefer something direct:

https://github.com/kiali/kiali/issues/4133#issuecomment-899398084

But I agree that adding a tour + another shortcuts info entry may result in too overloaded, so +1 to put it in the tour.

2021-09-24 14:23 UTC, leandroberetta commented
The following is a test without any description but a different tooltip:

![shortcuts2](https://user-images.githubusercontent.com/1286393/134690624-258503e4-c451-455a-b2ba-e1a5eaf63675.png)

2021-09-27 14:35 UTC, leandroberetta commented
@lucasponce @jshaughn I'm converting this draft into a proper PR for review:

![shortcuts4](https://user-images.githubusercontent.com/1286393/134929700-e7f8ec89-f96e-44ee-963f-682b16477601.png)

2021-09-29 19:27 UTC, jshaughn approved these changes
Looks great, and now we have html option for tour stop.

2021-09-30 09:50 UTC, lucasponce requested changes
The tour is great, I have a couple of minor comments about the style, as it's hard to test it and we need to rely manually on it.

![image](https://user-images.githubusercontent.com/1662329/135429418-249aba5b-766b-41f5-a63d-7003cbd1f631.png)

I'd not use the Grid for render the items, it's not flexible for minor panels like this and it creates situations where the margin/padding from the items looks greater. I'd take same marging that you can see in the toolbox (i.e. same margin used between Namespace and Display combobox). I'd use a simple render of divs that you can set your own style for margin.

Another style comment, I'd use font 14px for the description instead of 16px, otherwise it looks different with the next tour:

![image](https://user-images.githubusercontent.com/1662329/135429768-01333b22-60d3-49d7-897a-de2c3a2247cf.png)

But +1, it looks very nice to see this in the first step of the tour, I've also found it very useful.

2021-09-30 12:48 UTC, leandroberetta commented
@lucasponce thanks for your recommendations, I tried to used a combination of table + divs resulting in the following:

![shortcuts5](https://user-images.githubusercontent.com/1286393/135457556-df8a75b9-d647-42bf-bd61-207356050b39.png)

As you can see, I'm using the margin recommended but when text wrapped, the margin between the rows, increased, as the outer canvas is fixed always to a certain width, is this ok for you?. 

Also the size of the text is equal to the following tour steps.

2021-09-30 19:25 UTC, leandroberetta commented
New version with @lucasponce suggestions:

![shortcuts6](https://user-images.githubusercontent.com/1286393/135518015-0c80cfbb-8ee1-416f-aa38-db9fbb0054bc.png)

2021-10-01 08:35 UTC, lucasponce commented
Thanks @leandroberetta I put an ultra minor change in a https://github.com/leandroberetta/kiali-ui/pull/3 just to align a little bit.

Let me know what do you think and we can consolidate it.

2021-10-01 11:32 UTC, leandroberetta commented
> Thanks @leandroberetta I put an ultra minor change in a [leandroberetta#3](https://github.com/leandroberetta/kiali-ui/pull/3) just to align a little bit.
> 
> Let me know what do you think and we can consolidate it.

@lucasponce thanks for the fix, it's merged now.

2021-10-01 12:15 UTC, lucasponce approved these changes

2021-10-01 12:28 UTC, merged

2021-10-05 07:20 UTC, skondkar commented
Polarion Testcase ->> SWSQE-1995